# Generated by Django 2.2.7 on 2019-11-10 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavotite',
            new_name='UserFavorite',
        ),
    ]
