# Generated by Django 2.2.7 on 2019-11-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
    ]
